<?php
//=========================================================================
$P_EDIDAY = $infoweb["editplayershareday"];
if($P_EDIDAY == "Monday")$P_EDIDAY = "Senin";
else if($P_EDIDAY == "Tuesday")$P_EDIDAY = "Selasa";
else if($P_EDIDAY == "Wednesday")$P_EDIDAY = "Rabu";
else if($P_EDIDAY == "Thursday")$P_EDIDAY = "Kamis";
else if($P_EDIDAY == "Friday")$P_EDIDAY = "Jum`at";
else if($P_EDIDAY == "Saturday")$P_EDIDAY = "Sabtu";
else if($P_EDIDAY == "Sunday")$P_EDIDAY = "Minuggu";
$P_EDITIM1 = $infoweb["editplayersharetime1"];
$P_EDITIM2 = $infoweb["editplayersharetime2"];
$P_NEWPLA="Tambah Pemain";
$P_PLALIS="Nama Pemain ";
$P_ADDTRA="Add Transaction";
$P_DAIREP="Daily Player Report";
$P_RUNBET="Running Bet";
$P_CLOBET="Closing Bet";
$P_MEM="Memo";
$P_ONLLIS="Member Online";
$P_LOG="Catatan Log";
$P_CHAPAS="Ganti Password";
$P_OVE="Overview";
$P_OFF="Keluar";
$P_BANKLIST="Bank List";
$P_GAMCON="Kontrol Game";
$P_REGLINK="Link Register";
$P_HISCOI="History Koin";
$P_TUTO="Panduan";
$P_ALL ="Semua";
define("P_TRXDAY","Transaksi dimulai");
define("P_DAY","Hari");
define("P_MONTHLY","Bulanan");
define("P_REFLIS","Nama Referral");
define("P_CLI","Klik");
define("P_PAY","Bayar");
define(P_WLREF,"WL Referral");
define(P_REF,"Referral");
define(P_AREFSMCOM,"S.Master Referral ");
define(P_CLEANSMCOM,"Komisi Bersih S.Master");
define(P_GROSSSMCOM,"Komisi Kotor S.Master ");
define(P_AREFSMCOM,"S.Master Referral ");
define(P_AREFCOM,"Referral");
define(P_AREFAGECOM," Referral Agent");
define(P_AREFMASCOM," referral Master");
define(P_CLEANMASCOM," Komisi Bersih Master");
define(P_GROSSMASCOM,"Komisi Kotor Master");
define(P_REFERR,"Referer");
define(P_TOTREFPLA,"Total Referral");
define(P_UPREFCOM,"Komisi Referral Upline");
define(P_CLEANAGECOM," Komisi Bersih Agent");
define(P_GROSSAGECOM,"Komisi Kotor Agent");
define(P_MONTHSTR,"Bulan mulai");
define(P_MONTHEND,"Month akhir");
define(P_ALL,"Semua");
define(P_DAIREP,"Harian Pemain");
define(P_RUNBET,"Transaksi Berjalan");
define(P_CLOBET,"Transaksi Lengkap");
define(P_PAGTIT,"Page/Link Title");
define(P_PAGFIL,"Page File");
define(P_USELEV,"User Level");
define(P_REGLINK,"Registration Link");
define("P_ADDPRS","Tambah Anggota");
define(P_SUC,"Sukses");
define(P_TUTO,"Panduan");
define(P_BANKLIST,"Bank List");
define(P_GROUP,"Grup");
define(P_OP,"Alias");
define(P_PAGTIT,"Page/Link Title");
define(P_PAGFIL,"Page File");
define(P_OPRIGHT,"Operator akses");
define(P_PST,"Posisi");
define(P_14DRECORD,"Hanya dapat Melihat Transaksi 14 Hari terakhir.");
define(P_BILL,"Tagihan");
define(P_SUCDEL,"Berhasil hapus user");
define(P_BACK,"Kembali kehalaman Transaksi");
define(P_AGECOM,"Komisi Agent");
define(P_MASCOM,"Komisi Master");
define(P_SMCOM,"Komisi S.Master");
define(P_ARESUR,"Apakah anda yakin ingin menghapus user ini?");
define(P_CANDEL,"Tidak dapat menghapus user ini, masih tersisa transaksi 3 bulan terakhir.");
define(P_SPEREP,"Laporan Khusus");
define(P_TRA,"Transfer");
define(P_ERRDAT,"tanggal yang dipilih harus satu hari sebelum");
define(P_NEWMAS,"Tambah Master");
define(P_MASLIS,"Nama Master");
define(P_MASLISL,"Nama Master(blokir)");
define(P_NEWAGE,"Tambah Agen");
define(P_AGELIS,"Nama Agen");
define(P_AGELISL,"Nama Agen (blokir)");
define(P_NEWPLA,"Tambah Pemain");
define(P_PLALIS,"Nama Pemain");
define(P_PLALISL,"Nama Pemain (blokir)");
define(P_ADDTRA,"Tambah Transaksi");
define(P_REP,"Laporan");
define(P_DAIREP,"Harian Pemain");
define(P_RUNBET,"Transaksi Berjalan");
define(P_CLOBET,"Transaksi Lengkap");
define(P_INV,"Transaksi Pemain");
define(P_PRO,"Pendapatan");
define(P_TOO,"Perangkat");
define(P_MEM,"Memo");
define(P_ONLLIS,"Member Online");
define(P_LOG,"Catatan Log");
define(P_CHAPAS,"Ganti Password");
define(P_ACC,"Account");
define(P_OVE,"Overview");
define(P_OFF,"Keluar");
define(P_INPMAS,"Tambah Master");
define(P_ACCINF,"Account Info");
define(P_USE,"UserId");
define(P_PAS,"Password");
define(P_STA,"Status");
define(P_UNL,"Aktif");
define(P_LOC,"Blokir");
define(P_DATINF,"Data Info");
define(P_FUL,"Nama Lengkap");
define(P_ADR,"Alamat");
define(P_EMA,"Email");
define(P_PHO,"Telepon");
define(P_REM,"Keterangan");
define(P_BANNAM,"Nama Bank");
define(P_ACCNO,"Nomor Rekening");
define(P_ACCNAM,"Nama Rekening");
define(P_SHAINF,"Info Saham");
define(P_GIVCOI,"Koin Yang Diberikan");
define(P_REMCOI,"Koin Tersisa");
define(P_ADDMAS,"Tambah Master");
define(P_TEM,"Template");
define(P_SUPSHA,"Saham Super Master");
define(P_MAXMASSHA,"Maks. Saham Master");
define(P_COMWIN,"Komisi Menang");
define(P_COMLOS,"Komisi Kalah");
define(P_SHA,"Saham");
define(P_COPTEM,"Copy Dari Template");
define(P_ALO,"Alokasi");
define(P_MAXCOMWIN,"Max. Komisi Menang");
define(P_MAXCOMLOS,"Max. Komisi Kalah");
define(P_SEA,"Cari");
define(P_WINLOSE,"Menang/kalah");
define(P_TOT,"Total");
define(P_NO,"No");
define(P_DOW,"Bawahan");
define(P_COMMAS,"Komisi Master");
define(P_INPPLA,"Tambah Pemain");
define(P_MAX10CHA,"Maks 10 Karakter");
define(P_SUPTAKSHA,"S.Master Ambil Saham");
define(P_ADDPLA,"Tambah Pemain Baru");
define(P_PLASHA,"Saham Pemain");
define(P_BAN,"Bank");
define(P_BAL,"Balance");
define(P_COMPLA,"Komisi Pemain");
define(P_DEP,"Deposit");
define(P_WIT,"Withdraw");
define(P_HIS,"History");
define(P_COI,"Koin");
define(P_LIM,"Batas");
define(P_ALRCON,"Telah Diproses");
define(P_FATERR,"Kesalahan Fatal");
define(P_BALPRO,"Masalah Balance");
define(P_COIPRO,"Masalah Coin");
define(P_REJ,"Ditolak");
define(P_DEL,"Dihapus");
define(P_DAT,"Tanggal");
define(P_REQ,"Permintaan");
define(P_ISI,"Isi");
define(P_AMO,"Jumlah");
define(P_KET,"Keterangan");
define(P_NOREQ,"Tidak Ada Permintaan Baru.");
define(P_NOHIS,"Tidak Ditemukan History.");
define(P_TRAIN,"Transfer Kedalam");
define(P_TRAOUT,"Transfer Keluar");
define(P_COR,"Perbaikan");
define(P_CONHIS,"Pengaturan History");
define(P_APPDAT,"Tanggal Terima");
define(P_REQDAT,"Tanggal Permintaan");
define(P_TO,"Untuk");
define(P_HISCOI,"History Koin");
define(P_INF,"Info");
define(P_LAS,"Terakhir");
define(P_EMPTRA,"Transaksi Kosong");
define(P_PLEWAI,"Tolong Tunggu");
define(P_SUCTRA,"Berhasil Tambah Transaksi Baru");
define(P_ERRCRE,"Kredit Salah");
define(P_EXCLIM,"Lewat Batas");
define(P_PLECHEAGA,"Tolong Periksa Kembali");
define(P_PLECHEAMO,"Tolong Periksa Jumlah");
define(P_PLEFIl,"Tolong Isi");
define(P_PLECHEUSE,"Tolong Periksa UserId");
define(P_ERR,"Salah");
define(P_USEMUSDEP,"UserId Harus User Deposit");
define(P_NOTENO,"Tidak Cukup");
define(P_ACCDENACT,"Akses ditolak. Tidak Dapat Melakukan Aktivitas Ini.");
define(P_DETTRAHOL,"Ada Transaksi Gantung");
define(P_CHASTAREJ,"Pengubahan Status Ditolak");
define(P_NEWTRA,"Transaksi Baru");
define(P_PLATRA,"Transaksi Pemain");
define(P_CAN,"Batal");
define(P_SETCRE,"Ubah Jadi Kredit");
define(P_MIN,"Min");
define(P_MAX,"Maks");
define(P_BANFORDEP,"Bank Untuk Deposit");
define(P_PLADAIREP,"Laporan Harian Pemain");
define(P_DATSTR,"Tanggal Awal");
define(P_DATEND,"Tanggal akhir");
define(P_CUR,"Mata Uang");
define(P_TUR,"TurnOver");
define(P_WIN,"Menang");
define(P_LOS,"Kalah");
define(P_NIL,"* Nilai Ini Adalah Nilai Koin.");
define(P_BACREP,"Kembali Ke Laporan Utama");
define(P_GAM,"Game");
define(P_SUB,"SubTotal");

define(P_MASID,"Id Master");
define(P_COM,"Komisi");
define(P_GIV,"Yang Diberikan");
define(P_CMP,"Perusahaan");
define(P_GTY,"Tipe Game");
define(P_CLD,"* Closing : Senin Sampai Rabu Dan Kamis Sampai Minggu.");
define(P_PER,"Periode");
define(P_PLAID,"Id Pemain");
define(P_PLA,"Pemain");
define(P_TAB,"Tabel");
define(P_TIM,"Waktu");
define(P_PRI,"hadiah");
define(P_ROO,"Kamar");
define(P_BETNUM,"Nomor Bet");
define(P_NUMOUT,"Nomor Keluar");
define(P_BETON,"BetOn");
define(P_SENTO,"Kirim Untuk");
define(P_SUJ,"Subjek");
define(P_SENBOX,"Kotak Terkirim Anda Kosong.");
define(P_EMO,"Emoticons");
define(P_CMM,"Komentar");
define(P_RPL,"Balas");
define(P_FRO,"Dari");
define(P_MES,"Pesan");
define(P_MEMBOX,"Kotak Memo Anda Kosong");
define(P_LOGTIM,"Waktu Masuk");
define(P_SHALOG,"Log Saham");
define(P_OTHLOG,"Log Lain");
define(P_ACT,"Tindakan");
define(P_DET,"Detail");
define(P_MAXSHA,"Maks. Saham");
define(P_CRE,"Kredit");
define(P_EMPFOR,"Bagian Form kosong");
define(P_NOTMAT,"Tidak Cocok");
define(P_CANBLA,"Tidak Bisa Kosong");
define(P_OLDPAS,"Password Lama");
define(P_NEWPAS,"Password Baru");
define(P_CONNEWPAS,"Konfirmasi Password Baru");
define(P_CANPAS,"Password Ini Tidak Bisa Digunakan");
define(P_JOIDAT,"Tanggal Gabung");
define(P_DIS,"Diskon");
define(P_LAN,"Bahasa");
define(P_INPAGE,"Masukkan Agen");
define(P_ADDAGE,"Tambah Agen");
define(P_MAXAGESHA,"Maks. Saham Agen");
define(P_MASTAKSHA,"Master Ambil Saham");
define(P_MASSHA,"Saham master");
define(P_ALLGAM,"Semua Game");
define(P_AGEID,"Id Agent");
define(P_IP,"IP");
define(P_AGETAKSHA,"Agent Ambil Saham");
define(P_AGESHA,"Saham Agen");
define(P_YOURIG,"Anda Tidak Berhak");
define(P_DATSUC,"Data Telah Berhasil Diubah");
define(P_PLECHESHA,"Tolong Periksa Saham");
define(P_CANUNL,"Tidak Dapat Membuka");
define(P_PLECHECOM,"Tolong Periksa Komisi");
define(P_RETPAS,"Password Konfirmasi");
define(P_NEWPASFOR,"Password Baru Untuk");
define(P_HASSUCCHA,"Telah Berhasil Diubah");
define(P_EDI,"Ubah");
define(P_BACCOL,"Warna Latar");
define(P_CHA,"Ganti");
define(P_TYP,"Tipe");
define(P_COMERR,"Salah Komisi.");
define(P_GEN,"Umum");
define(P_REJERR,"Salah Penolakan");
define(P_ACTBAL,"Balance aktif, Tidak Dapat Mengubah Kredit");
define(P_SHAERR,"Salah Saham");
define(P_YOUTIM,"Anda tidak Diizinkan Mengubah Pada Saat Ini.<br>Anda dapat mengubah pada hari ".$P_EDIDAY." jam ".$P_EDITIM1.":00 sampai ".$P_EDITIM2.":00");
define(P_REPDET,"Laporan Detail");
define(P_HEL,"Bantuan");
define(P_HELDAIREP,"Laporan yang dicatat dari segala aktivitas yang dilakukan pemain didalam game setiap hari( untuk level pemain saja).");
define(P_HELRUNBET,"Menampilkan laporan transaksi berjalan (aktif).");
define(P_HELCLOBET,"Menampilkan laporan transaksi setiap periode perhitungan antara level atasan dengan bawahan. Berdasarkan nilai tersebut, semua pihak saling mencocokan laba dan ruginya.");
define(P_HELINV,"Menampilkan detail per transaksi/betting dari seorang player.");
define(P_HELPRO,"Menampilkan nilai win/lose dari game yang sedang berjalan.");
define(P_HELCONHIS,"Menampilkan nilai rekaman transaksi lama dari proses deposit, tarik deposit, koreksi yang dilakukan terhadap seorang pemain.");
define(P_HELHISCOI,"Melihat transaksi permintaan coin ataupun penarikan coin yang dilakukan oleh supermaster,master dan agen.");
define(P_HELNEWTRA,"Penambahan transaksi baru misalnya deposit, tarik deposit dari seorang pemain atau level supermaster, master dan agen");
define(P_HELNEWPLA,"Silakan membuat player yang posisinya langsung ditempatkan dibawah anda");
define(P_HELPLALIS,"Menampilkan nama pemain/player");
define(P_HELPLALISL,"Menampilkan nama pemain/player yang diblokir");
define(P_HELNEWMAS,"Membuat Master Baru");
define(P_HELMASLIS,"Menampilkan nama Master");
define(P_HELMASLISL,"Menampilkan nama Master yang diblokir");
define(P_HELNEWAGE,"Membuat Agen Baru");
define(P_HELAGELIS,"Menampilkan nama Agen");
define(P_HELAGELISL,"Menampilkan nama Agen yang diblokir");
define(P_UPL,"Upline");
define(P_PLAPT,"Player PT");
define(P_PRF,"Profil");
define(P_NOTCOR,"Note : jika anda ingin mengurangi Coin maka ketik tanda kurang ( - ) di depan angka !<br>jika anda ingin menambah Coin maka langsung ketik angka.");
define(P_WITAPP,"Tarik Deposit Disetujui");
define(P_DEPAPP,"Deposit Disetujui");
define(P_DEPREJ,"Deposit Ditolak");
define(P_WITREJ,"Tarik Deposit Ditolak");
define(P_WITREQ,"Permintaan Tarik Deposit");
define(P_DEPREQ,"Permintaan Deposit");
define(P_DENHOR,"Dengan hormat,");
define(P_KAMTELKIR,"Kami telah mengirimkan dana sebesar");
define(P_SESMINTAR,"sesuai permintaan penarikan yang anda lakukan.");
define(P_DANMASACC,"Dana tersebut sudah masuk ke account bank anda(sesuai account yang ada dalam database kami).");
define(P_HORKAM,"Hormat kami");
define(P_MAN,"Manajemen");
define(P_KAMTELTER,"Kami telah menerima deposit anda sebesar");
define(P_DANTAMBAL,"Dana tersebut telah ditambahkan pada balance anda.");
define(P_SETTAHVER,"setelah melalui beberapa tahap verifikasi<br>kami menolak atau membatalkan permintaan tarik deposit.<br>Tarik deposit anda dikembalikan sebanyak");
define(P_SETTAHVERX,"setelah melalui beberapa tahap verifikasi<br>kami menolak atau membatalkan terlebih dahulu permintaan<br>penambahan dana sebanyak");
define(P_SETTAHVER2,"coin.<br>silahkan hubungi kami kembali.");
define(P_BATMINDEP,"membatalkan permintaan deposit anda sebesar");
define(P_JIKTANHAL,"Jika anda memiliki pertanyaan tentang hal ini, silakan menghubungi kami kembali");
define(P_BATMINTAR,"membatalkan permintaan penarikan dana sebesar");
define(P_PLAREQ,"Permintaan Pemain");
define(P_MASREQ,"Permintaan Master");
define(P_AGEREQ,"Permintaan Agent");
define(P_PAYMET,"Metode Pembayaran");
define(P_CHOPAYMET,"== Pilih Metode Pembayaran ==");
define(P_CAS,"Cash");
define(P_ATM,"ATM");
define(P_INTBAN,"Internet Banking");
define(P_MOBBAN,"Mobile Banking");
define(P_SEN,"Kirim");
define(P_DEPINPRO,"Deposit Dalam Proses..");
define(P_BLACOLB,"Anda Harus Memasukkan Data Dengan Benar, Semua Kolom Harus Diisi. Mohon Klik Disini <a href='deposit.php'>Back</a>");
define(P_BLACOLW,"Anda Harus Memasukkan Data Dengan Benar, Semua Kolom Harus Diisi. Mohon Klik Disini <a href='withdraw.php'>Back</a>");
define(P_TQCON,"Terima Kasih Atas Konfirmasi Pembayaran Anda. <Br>Kami Akan Menghubungi Kembali Setelah Dana Diterima.");
define(P_TQ,"Terima Kasih Atas Konfirmasi Pembayaran Anda.");
define(P_DEPINPRO,"Tarik Deposit Dalam Proses..");
define(P_CANUSETHIPAS,"Tidak diijinkan mempergunakan password");
define(P_CANUSETHIID,"Tidak diijinkan mempergunakan UserId in");
define(P_SUCCESS,"Sukses");
define(P_AGENT,"Agent");
define(P_PLAYER,"Pemain");
define(P_MASTER,"Master");
define(P_SMASTER,"SuperMaster");
define(P_TRANSACTIONFOR,"Khusus Transaksi dengan");
define(P_WITINPRO,"Penarikan dalam antrian");
define(P_QUEUE,"Sedang Antri");
define(P_ALREXI,"Sudah Ada");
define(P_MINTARDAN,"Permintaan penarikan dana anda akan segera kami proses.");
define(P_MINTAMDAN,"Permintaan penambahan dana anda akan segera kami proses.");
define(P_SLI,"Slip");
define(P_MEMKIROTO,"(Memo ini dikirim otomatis, berkaitan dengan penarikan dana.)");
define(P_MEMKIROTOX,"(Memo ini dikirim otomatis, berkaitan dengan permintan deposit.)");
define(P_PAYDAT,"Tanggal Bayar");
define(P_OPE,"Operator");
define(P_FAI,"Gagal");
define(P_PASLEN,"Password minimal 5 digit");
define(P_HURANG,"Password harus ada huruf dan angka");
define(P_GAMCON,"Kontrol Game");
define(P_RUNTEXT,"Running Text");
define(P_RULE,"Peraturan");
define(P_USRLEN,"userid Maximum  10 digit");
define(P_SETT,"Pengaturan");
define(P_RUNTEXT,"Text Berjalan");
define(P_NEWS,"Berita");
define(P_RULES,"Peraturan");
define(P_HOWTOPLAY,"Cara Bermain");
define(P_STATIS,"Statistik");
//=========================================================================
//GAME
//=========================================================================
define(P_LOBBY, "Lobby");
define(P_MOBILE, "Mobile");
define(P_LOGOUT, "Keluar");
define(P_REGISTER, "Daftar");
define(P_HOME, "HOME");
define(P_JACKPOT, "Jackpot");
define(P_HELP, "Bantuan");
define(P_PLAYNOW, "Play Now");
define(P_HOWTOPLAY, "Cara Bermain");
define(P_REGISTERHERE, "Daftar Sekarang");
define(P_WINNER, "Pemenang");
define(P_LATESTROYALFLUSH, "RoyalFlush Terbaru");
define(P_CONGRATULATION, "Selamat");
define(P_LATESTDEPOSIT, "Deposit Terbaru");
define(P_LATESTWITHDRAW, "Withdraw Terbaru");
define(P_LATESTNEWS, "Berita Terbaru");
define(P_FORGETPASSWORD, "Lupa Password");
define(P_lOGIN, "Masuk");
define(P_WELCOME, "Selamat Datang");
define(P_MAX, "maismal");
define(P_MIN, "minimal");
define(P_USERNAME,"Username");
define(P_CHAR,"karakter");
define(P_PLEASE,"Mohon");
define(P_CONTACTUS,"Hubungi Kami");
define(P_THANKYOU,"Terima Kasih");
define(P_YOURACCOUNTNAME,"Akun Anda");
define(P_YOURACCOUNTPASSWORD,"Password Anda");
define(P_RETYPEPASSWORD,"ulangi password");
define(P_PASSWORDCONFIRMATION,"Konfirmasi password anda");
define(P_YOURFULLNAME,"Nama lengkap anda");
define(P_YOURPHONENUMBER,"Nomor telepon anda");
define(P_BANKACCOUNTNAME,"Akun bank anda");
define(P_BANKACCOUNTNUMBER,"Nomor akun bank");
define(P_YOURBANKACCOUNTNUMBER,"Nomor akun bank anda");
define(P_YOURBANKACCOUNTNAME,"Nama lengkap akun bank anda");
define(P_NOTCOMPULSORY,"Tidak wajib");
define(P_CAPTCHA,"Captcha");
define(P_USER,"Akun");
define(P_REGISTRATIONDATE,"Tanggal pendaftaran");
define(P_COMMISSION, "komisi");
define(P_POKERANDROIDVERSION, "Poker Mobile");
define(P_POKERANDROID,"Poker Android");
define(P_POKERIOS,"Poker iPhone");
define(P_INSTALLATIONINSTRUCTION,"Petunjuk installasi");
define(P_DOWNLOADFILE,"Download file");
define(P_SIZE,"Ukuran");
define(P_AFTERDOWNLOAD,"Setelah mendownload aplikasi android ( ukuran file harus sama dengan info ), kemudian buka my file &gt; All File &gt; Download dan jalankan file");
define(P_IFCANTDOINSTALL,"Jika gagal menginstall aplikasi, bukalah setting &gt; Security, dan aktifkan the unknown source");
define(P_AFTERINSTALL,"Setelah berhasil menginstall aplikasi, sekarang anda dapat memainkannya.");
define(P_BESTVIEW,"Untuk tampilan yang lebih bagus, harap gunakan layar diatas 4 inchi");
define(P_LASTESTINFO, "Info Terbaru");
define(P_MAINTENANCEPROCESS, "Kami sedang dalam perbaikan");
define(P_SENDER,"Pengirim");
define(P_VALIDATION,"Validasi");
define(P_DESTINATION, "Destinasi");
define(P_YOURACCPASSWORD ,"Password akun anda");
define(P_STARTDATE ,"Tanggal awal");
define(P_ENDDATE ,"Tanggal akhir");
//=========================================================================
//REFERRAL
//=========================================================================
define(P_PROMOTIPS, "Tips promosi");
define(P_SHAREREFLINKVIAFORUM,"Anda bisa menyebarkan link referral anda ke FORUM.");
define(P_TWEETREFERRALLINK,"Bisa juga dengan mentweet link referral anda di TWITTER.");
define(P_DOCOMENTONFACEBOOK,"Melakukan posting komentar di FACEBOOK.");
define(P_PUTYOURLINKATBLOG,"Memasang link referral anda anda di BLOG.");
define(P_SHARELINKTOCONTACT,"Menyebarkan link referral kesemua contact EMAIL.");
define(P_HOWTOCHECKREFERRAL,"Bagaimana cara melihat komisi referral anda");
define(P_LOGINTO,"Masuk melalui");
define(P_CLICKREFERRAL,"Tekan referral untuk melihat total referral");
define(P_CLICKCOMMISSION,"Tekan komisi untuk melihat total komisi");
define(P_WITHDRAWREFERRAL, "Komisi referral akan di bagikan setiap hari kamis");

//=========================================================================
//end referral
//=========================================================================

//=========================================================================
//Deposit
//=========================================================================
define(P_DEPOFAILOUTGAME,"Gagal deposit, harap keluar dari game terlebih dahulu");
define(P_ONEPENDINGDEPO,"Deposit gagal, anda masih memiliki 1 pending deposit");
define(P_DEPOFAILFILLAMOUNT,"deposit gagal, harap perkisa kembali jumlah yang anda input");
define(P_DEPOFAILFILLDATE,"Deposit gagal, harap isi tanggal");
define(P_DEPOFAILFILLSENDTIME,"Deposit gagal, harap mengisi tanggal kirim");
define(P_DEPOFAILFILLACCNAME,"Deposit gagal, harap ini nama akun anda");
define(P_DEPOFAILFILLBANKACCNO,"Gagal deposit, harap isi nomor akun anda.");
define(P_DEPOFAILFILLBANKNAME,"Gagal deposit, harap isi nama bank");
define(P_DEPOFAILCHOOSEBANK,"Gagal deposit, harap pilih bank tujuan");
define(P_DEPOFAILREMAK,"Gagal deposit, harap isi keterangan");
define(P_DEPOFAILMAXDEPO,"Gagal deposit, maksimal deposit adalah ");
define(P_DEPOFAILMDEPO,"Gagal deposit. minimal deposit adalah ");
define(P_DEPOFAILAMOUNT,"Gagal deposit. Harap isi jumlah");
define(P_DEPOFAIL,"Gagal deposit");
define(P_BANKACCDESTINATOIN,"Bank tujuan");
define(P_YOURDEPOMAXPROCESS,"Deposit anda akan di proses dalam waktu 24 jam");
define(P_CHECKACTIVEBANK, "HARAP SELALU MEMERIKSA REKENING YANG AKTIF SEBELUM MELAKUKAN PENGIRIMAN");
define(P_DONTACCEPTBANK, "Kami tidak menerima deposit atas nama orang lain");
define(P_AMOUNTDEPOSIT, "Jumlah deposit");
//=========================================================================
//end deposit
//=========================================================================

//=========================================================================
//withdraw
//=========================================================================
define(P_WITHDRAWFAIL,"Gagal withdraw");
define(P_DONTENTERGAME,"Harap keluar dan pastikan anda tidak sedang bermain game apapun");
define(P_PLEASEFILLPASSWORD, "Harap isi password");
define(P_PLEASEFILLAMOUNT, "Harap isi jumlah");
define(P_MINWITHIS, "Minimal withdraw adalah");
define(P_MAXWITHIS, "maksimal withdraw adalah");
define(P_WITHDRAWSUCCESS, "Withdraw berhasil");
define(P_WITHDRAWREQPROCESS, "Withdraw anda akan di proses dalam waktu 24 jam ");

//=========================================================================
//end Withdraw
//=========================================================================

//=========================================================================
//forget password
//=========================================================================
define(P_WRONGDATA,"Kesalahan data!");
define(P_USERNAMEINPROCESS,"permintaan ganti password sedang diproses");
define(P_PLEASEFILLCAPTCHA, "Harap isi captcha");
define(P_ONLYCANUSEFORGETPASSWORD, "Anda tidak boleh login dalam waktu 24 jam untuk melakukan lupa password");
define(P_PASSCHANGEDTO, "Password anda telah berganti menjadi");
define(P_PLEASELOGINAGAIN, "Harap masuk kembali dengan mengunakan password. ( perhatikan huruf besar dan kecil )");
define(P_REQUESTSEND, "Permintaan anda telah di kirim");
define(P_YOURACCUSERID, "ID akun anda adalah");

//=========================================================================
//end forgetpassword
//=========================================================================


//=========================================================================
//ERROR OR MESSAGE
//=========================================================================
define(P_CANTOPENPAGE, "Tidak dapat membuka halaman");
define(P_REGISTRATIONCLOSED, "Pendaftaran ditutup sementara");
define(P_VALIDATIONWRONG, "Validasi salah");
define(P_REGISTRATIONFAILED, "Registrasi gagal");
define(P_USERALREADYREGISTERED, "Userid telah terdaftar");
define(P_BANKACCOUNTNUMBERERROR, "ilegal karakter pada kolom nomor akun bank");
define(P_FIRSTCHARMUSTBETAZ, "huruf pertama haruslah A - Z");
define(P_PLEASECHECKEMAIL, "Harap periksa email");
define(P_PLEASEFILLALLFIELD, "Harap isi semua kolom yang ada");
define(P_WRONGUSERNAME, "Kesalahan username");
define(P_PLEASECHECKBANKNAME, "Periksa kembali nama bank");
define(P_BANKREGISTRATIONFAILED, "Registrasi bank gagal");
define(P_WRONGREFERRAL, "Referral ID anda salah");
define(P_EMAILEXIST, "Email ini sudah pernah digunakan");
define(P_BANKACCOUNTEXIST, "Akun bank ini sudah pernah digunakan");
define(P_REGISTERSUCCESS, "Registrasi berhasil");
define(P_PLEASELOGINAT, "Harap masuk melalui");
define(P_YOUCANDODEPOSIT, "Anda dapat melakukan deposit di ");
define(P_FROMYOURAGENT, "atau melalui agent anda");
define(P_PLEASELOGINFORDEPOSIT, "Harap login untuk deposit");
define(P_PLEASELOGINFORWITHDRAW, "Harap login untuk withdraw");
//-- INDO BANK
define(P_BCA10DIGIT, "Nomor akun bank BCA haruslah 10 digit");
define(P_MANDIRI13DIGIT, "Nomor akun bank MANDIRI harusnya 13 digit");
define(P_BNI10DIGIT, "Nomor akun bank BNI haruslah 10 digit");
define(P_MANDIRI13DIGIT, "Nomor akun bank BRI haruslah 15 digit");
//-- END

//=========================================================================
//NEW LOBBY REQUIREMENT
//=========================================================================
define(P_GLOBALJACKPOT, "GLOBAL JACKPOT");
define(P_FASTTABLE, "FAST TABLE");
define(P_SMALLEST, "SMALLEST");
define(P_SMALL, "SMALL");
define(P_MEDIUM, "MEDIUM");
define(P_LARGE, "LARGE");
define(P_VIP, "VIP");
define(P_MINBUY, "Min Buyin");
define(P_MAXBUY, "Max Buyin");
define(P_BLIND, "Blind");
define(P_HIDEFULLTABLE, "Hide Full Table");
define(P_ONLINEPLAYER, "Online Players");
define(P_FULLTABLE, "Full Table");
define(P_CHANGEAVATAR, "CHANGE AVATAR");
define(P_BROWSE, "BROWSE");
define(P_NOFILE, "NO FILE SELECTED");
define(P_UPLOAD, "UPLOAD");
define(P_SUG, "Suggested size is 100 x 100 pixel");
define(P_CHOOSE, "CHOOSE");
define(P_PLAYERCARD, "Player Card");
define(P_WINNERCARD, "Winner Card");
define(P_DEALERCARD, "Dealar Card");
define(P_LATESTNEWS, "Latest News");
define(P_DEALER, "Dealer");
define(P_TEXASPOKER, "Texas Poker");
define(P_DOMINO, "Domino");
define(P_CEME, "Ceme");
?>